### PR TITLE
feat,test,style(Vector): Added conversion to dense representation and tests

### PR DESCRIPTION
**Pull request by sneakyweasel**
Went through Vector (noted issues with the FIXME, TODO code tag)

- FEAT: Implemented toDense(): Complex[][] export function
- TEST: Wrote tests for core functions
- STYLE: Reordered functions according to their arity and scope (getters, unary, binary)

Issues:

- size & totalSize: naming is confusing maybe sizes and length
- normSquared: should be a getter, also length, norm and abs are making naming confusing
- Bra & Ket distinction might be useful to avoid applying conj if unneeded
- dotPartial, innerPartial not implemented, remove _removeDimension
- outer product returns a v1.totalSize * v2.totalSize Vector, maybe naming could be better

### CODE REVIEW

**Comment by stared** [comment]
A few meta remarks:

* issue should be a separate issue (if you have suggestions for names, write them down)
* `style` -> `refactor`

**Comment by stared** [comment]
And please, please, please - ALL purely refactor things as separate. They generate a lot of lines of diffs, and it is practically impossible to review code that makes changes.

Also - why `/* eslint-disable-next-line */` with lodash? I didn't have an error and disabling should be a last resort, not some typical part of code.

Also - DON'T CALL IT PARTICLE. DON'T. As in `IParticle`. Particle has too many meanings and stuff.  But if... no, DON'T.

**Comment by sneakyweasel** [comment]
- It's lodash import making eslint whine: https://github.com/angular-fullstack/generator-angular-fullstack/issues/2549
- I used the same interface name as in QG2 what should IParticle be called?
- Maybe we should review naming conventions for quantum-tensors it feels confusing right now.

**Comment by stared** [comment]
(I am almost sure I commented it already - not sure if it wasn't sent, or through a different channel.)
I merge it, however:

* I didn't get the `lodash` error before
* even if, es lint disable lines should be as specific as possible
* Instead of `IParticle` I suggest something like `IPolarizationGathered`
* For naming conventions please open a separate issue, ideally with new name proposals

**Pull request merged**
